spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/beneficio_cafe
spring.datasource.username=postgres
spring.datasource.password=PIZZA

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=admin
spring.security.user.password=admin


# Mostrar errores reales
server.error.include-message=always
server.error.include-binding-errors=always

# Logging detallado
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.root=INFO

# Mostrar excepciones que Spring resuelve internamente
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=DEBUG

# Hibernate errores
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=ERROR
logging.level.org.springframework.dao=DEBUG